### ISSUE TITLE
Use the same OpenJDK and Maven version as ci.jenkins.io and trusted.ci.jenkins.io

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/docker-packaging#16]
The current image is installing `maven`: we don't know which version?
It also installs a JDK dependency, which we don't know the version as well.

We should stay as close as possible as the other Jenkins system of the infra: that would mean inheriting from the maven-11 or maven-8 container images instead.

**Comment by dduportal** [comment]
@timja @MarkEWaite what is the JDK major version required? 8, 11 or we don't care (so 17)?

**Comment by timja** [comment]
what is java needed for here?

**Comment by MarkEWaite** [comment]
I assume that maven is needed for some portion of the build process and Java is installed as a dependency of maven.  When I ran `ubuntu:18.04` and installed maven, it reports:

```
$ mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.19.0-18-amd64", arch: "amd64", family: "unix"
```

That's a maven version  that might be  viable, though as far as I know, we migrated everything to 3.8.x.

**Comment by dduportal** [comment]
There are portions of the release script using Maven (so a JDK is needed) such as https://github.com/jenkins-infra/release/blob/master/utils/release.bash#L354 .

I've tried to use a base image `maven:3-eclipse-temurin-11` yesterday, but it's based on `ubuntu:20.04` which changes a lot the package lists (some are "absent" such as `createrepo` because of the python mess - https://answers.launchpad.net/createrepo/+question/690448).

We could define a "static" installation (e.g. ARG with the version, maintained by updatecli, curl + unzip) that would ensure a decent version is used, but I'm more concerned about using the same set of SDKs than on ci.jenkins.io (e.g. same base).

**Comment by timja** [comment]
The release script uses a different image:

    image: "maven:3-jdk-8"

**Comment by dduportal** [comment]
Oh correct: https://github.com/jenkins-infra/release/blob/43f56a3b8faeffd58759eda189d5895cfa32c5a3/Jenkinsfile.d/core/package => the maven + java might be a remnant from the past (or the docker-packaging image is used somewhere else).

Should we try to remove maven + jdk instead (less dependencies, less weight less maintenance)?

**Comment by timja** [comment]
yeah we should I think

**Comment by timja** [comment]
unless @olblak remembers 😄

**Comment by dduportal** [comment]
> yeah we should I think

I mean, now that the image are versionned, it won't too painful for next weekly: if it fails, we rollback to the previous version and "etvoila"

**Comment by olblak** [comment]
> 

I am pretty confident that you can remove java from this image. The sole purpose of the docker packaging image is to run the packaging script. Initially, I was using the same docker image for running Maven release and the packaging script as it was done in the same pipeline job but then I improved by splitting that pipeline in two and then using the maven docker image for the release process as it's smaller

**Comment by lemeurherve** [comment]
Related: https://github.com/jenkins-infra/helpdesk/issues/2732

**Comment by dduportal** [comment]
For info, already done in #21
