### ISSUE TITLE
Don't publish empty releases

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/docker-packaging#47]
Hey,

according to the [releases tab](https://github.com/jenkins-infra/docker-packaging/releases), new tags are published on a weekly basis. 

Is there are particular reason, why releases are published if nothing changed? updatecli keeps filing PRs for those empty changes.

**Comment by timja** [comment]
I assume it's just rebuilding,

i.e. a number of packages aren't pinned so it's worthwhile to regularly rebuild:
https://github.com/jenkins-infra/docker-packaging/blob/d45621aedc978ac1fda46ae2d1cfe045d79be993/Dockerfile#L16-L40

**Comment by timja** [comment]
2 second check of the docs @dduportal 😂 

https://github.com/release-drafter/release-drafter/
```
no-changes-template
```

**Comment by lemeurherve** [comment]
As release-drafter is correctly filling release notes and as we need these releases to keep unpinned dependencies up to date, I'm closing this issue.
